spring:
  application:
    name: tp-cd-2024
  datasource:
    # Référence l'hôte et le port
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}&channel_binding=${DB_CHANNEL_BINDING}

    # Référence l'utilisateur et le mot de passe
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    # Configuration du driver
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
