name: CI/CD Pipeline

on:
  push:
    # Déclenche le workflow sur toutes les branches
    branches:
      - main
      - "*"
    # Exclut les changements uniquement dans le README pour ne pas relancer la CI/CD inutilement
    paths-ignore:
      - "README.md"

jobs:
  # =========================================================
  # CI JOB: Vérifications (S'exécute sur TOUTES les branches)
  # =========================================================
  ci:
    name: Continuous Integration Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Configuration Java ---
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      # --- 1. Run Unit Tests (Tests unitaires) ---
      - name: Run Maven Tests
        run: mvn test

      # --- 2. Check App Build with Docker (Vérification du Build Docker) ---
      - name: Build Docker Image (Check only)
        run: docker build -t wellannn/tp-check:latest .

  # ---------------------------------------------------------
  # CD JOB: Déploiement (S'exécute UNIQUEMENT sur 'main' après succès de la CI)
  # ---------------------------------------------------------
  cd:
    name: Continuous Deployment
    needs: ci # Démarre seulement si le job 'ci' a réussi
    runs-on: ubuntu-latest

    # Condition: Déclenche le CD uniquement si la branche est 'main'
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Docker Push (Déploiement sur Docker Hub) ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/2025-devops-cd:main

      # --- Netlify Deployment (Déploiement de la Documentation) ---
      - name: Deploy Documentation to Netlify
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=. --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # --- Render.com Deployment
      - name: Trigger Render Deploy (Web Service Update)
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Content-Type: application/json"
